version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: book_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_password
      MYSQL_DATABASE: book_management
      MYSQL_USER: wxapp_user
      MYSQL_PASSWORD: wxapp_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - book_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_backend
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: wxapp_user
      MYSQL_PASSWORD: wxapp_password
      MYSQL_DATABASE: book_manage
      JWT_SECRET: your_jwt_secret_key_here
    networks:
      - book_network

volumes:
  mysql_data:

networks:
  book_network:
    driver: bridge
